spring:
  config:
    activate:
      on-profile: k8s
  mail:
    protocol: smtp
    host: mailhog
    port: 1025
    username: test
    password: test
    properties:
      mail:
        from: test@example.com
  r2dbc:
    url: r2dbc:pool:mysql://mysql:3306/spring-boot-r2dbc-rest-sample?allowPublicKeyRetrieval=true&useSSL=false
  flyway:
    schemas: spring-boot-r2dbc-rest-sample
    url: jdbc:mysql://mysql:3306/?allowPublicKeyRetrieval=true&useSSL=false
    user: ${spring.r2dbc.username}
    password: ${spring.r2dbc.password}
    baseline-on-migrate: true
    placeholder-replacement: false
  data:
    redis:
      host: redis
      port: 6379
logging:
  level:
    org.springframework.r2dbc: INFO
springdoc:
  swagger-ui:
    enabled: true

####
# アプリケーションの設定
application:
  fileUploadLocation: /tmp/sample
  cors:
    allowed-headers: "Origin,X-Requested-With,Content-Type,Accept,X-XSRF-TOKEN"
    allowed-methods: "POST,GET,PUT,OPTIONS,DELETE"
    allowed-origins: "http://spring-boot-r2dbc-rest-sample.192.168.64.3.nip.io"
