spring:
  config:
    activate:
      on-profile: local
  messages:
    cache-duration: -1
  mail:
    protocol: smtp
    host: 127.0.0.1
    port: 1025
    username: test
    password: test
    properties:
      mail:
        from: test@example.com
  r2dbc:
    url: r2dbc:pool:mysql://127.0.0.1:3306/spring-boot-r2dbc-rest-sample?useSSL=false&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: passw0rd
  flyway:
    schemas: spring-boot-r2dbc-rest-sample
    url: jdbc:mysql://127.0.0.1:3306/?allowPublicKeyRetrieval=true&useSSL=false&useUnicode=true&characterEncoding=UTF-8
    user: ${spring.r2dbc.username}
    password: ${spring.r2dbc.password}
    baseline-on-migrate: true
    placeholder-replacement: false
  data:
    redis:
      host: 127.0.0.1
      port: 6379
logging:
  level:
    org.springframework.r2dbc: DEBUG
springdoc:
  swagger-ui:
    enabled: true

####
# アプリケーションの設定
application:
  fileUploadLocation: build/sample
  cors:
    allowedHeaders: "Origin,X-Requested-With,Content-Type,Accept,X-XSRF-TOKEN"
    allowedMethods: "POST,GET,PUT,OPTIONS,DELETE"
    allowedOrigins: "*"
